pipeline:
  build:
    image: elixir:1.7-alpine
    secrets: [ coveralls_repo_token ]
    commands:
      - apk add -qU git
      - mix local.hex --force
      - mix local.rebar --force
      - yes | mix deps.get
      - MIX_ENV=test mix coveralls.drone